services:
    hr-config-server:
        environment:
            - GITHUB_USER=walacetalesfs
            - GITHUB_PASS=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
        image: hr-config-server:v1
        container_name: hr-config-server
        build: 
            context: ./hr-config-server
            dockerfile: Dockerfile
        ports:
            - '8888:8888'
        healthcheck:
            test: curl http://localhost:8888/config-server/health
    hr-user-pg12:
        environment:
            - POSTGRES_PASSWORD=1234567
            - POSTGRES_DB=db_hr_user
        image: postgres:12-alpine
        container_name: hr-user-pg12
        ports:
            - '5433:5432'

    hr-eureka-server:
        image: hr-eureka-server:v1
        container_name: hr-eureka-server
        build:
            context: ./hr-eureka-server
            dockerfile: Dockerfile
        ports:
          - '8761:8761'
        healthcheck:
            test: curl http://localhost:8761/eureka-server/health
        depends_on:
          hr-config-server: 
            condition: service_healthy

    hr-user:
        image: hr-user:v1
        container_name: hr-oauth
        build: 
            context: ./hr-worker
            dockerfile: Dockerfile
        depends_on:
            hr-config-server: 
                condition: service_healthy
            hr-eureka-server: 
                condition: service_healthy
    
    hr-oauth:
        image: hr-oauth:v1
        build:
            context: ./hr-oauth
            dockerfile: Dockerfile
        depends_on: 
            hr-config-server: 
                condition: service_healthy
            hr-eureka-server: 
                condition: service_healthy

    hr-api-gateway-zuul:
        image: hr-api-gateway-zuul:v1
        container_name: hr-api-gateway-zuul
        build:
            context: ./hr-api-gateway-zuul
            dockerfile: Dockerfile
        ports:
          - '8765:8765'
        depends_on: 
            hr-config-server: 
                condition: service_healthy
            hr-eureka-server: 
                condition: service_healthy
#    hr-worker:
#        image: hr-config-server:v1
#        build: 
#            context: ./hr-worker
#            dockerfile: Dockerfile
#        network_mode: hr-net
